package test;

import app.view.MiniGameScreen;
import junit.framework.TestCase;

/**
 * The class <code>MiniGameScreenTest</code> contains tests for the class
 * {@link <code>MiniGameScreen</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/20/12 6:19 PM
 *
 * @author Andrew Wilder
 *
 * @version $Revision$
 */
public class MiniGameScreenTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public MiniGameScreenTest(String name) {
		super(name);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = test
 * package.sourceFolder = SpaceFarmer3000_3/src
 * superclassType = junit.framework.TestCase
 * testCase = MiniGameScreenTest
 * testClassType = app.view.MiniGameScreen
 */